### ISSUE TITLE
ImportError: cannot import name 'Panel' from 'pandas'

### ISSUE THREAD

**Issue by pxlogpx** [man-group/arctic#880]
#### Arctic Version
```
# 1.79.3 and 1.8.0
```

#### Arctic Store

```
# VersionStore, TickStore, or ChunkStore
```

#### Platform and version

Anaconda3-2020.11
Python : 3.7.9 and 3.8.5
numpy: 1.19.2
pandas: 1.2.0

#### Description of problem and/or code sample that reproduces the issue

Put Here

Steps : 
Installed Anaconda3-2020.11
Created a new environment with python 3.8.5
installed artic using : conda install -c conda-forge arctic
open a terminal on the new enviroment

> `>>> from arctic import Arctic
> 
> Traceback (most recent call last):
> 
>   File "<stdin>", line 1, in <module>
> 
>   File "C:\anaconda3\envs\gauss37\lib\site-packages\arctic\__init__.py", line 6, in <module>
> 
>     from .store._pandas_ndarray_store import PandasDataFrameStore, PandasSeriesStore, PandasPanelStore
> 
>   File "C:\anaconda3\envs\gauss37\lib\site-packages\arctic\store\_pandas_ndarray_store.py", line 6, in <module>
> 
>     from pandas import DataFrame, Series, Panel
> 
> ImportError: cannot import name 'Panel' from 'pandas' (C:\anaconda3\envs\gauss37\lib\site-packages\pandas\__init__.py)`
> 

Tried the same process with a python 3.7 env and installing arctic via : pip install git+https://github.com/manahl/arctic.git, same error in all situations.
**Update** Installing using a python 3.6.12 environment works in Anaconda

**Comment by pxlogpx** [comment]
Just saw the documentation that it works until python 3.6 :)

**Comment by bmoscon** [comment]
it works fine in 3.7, the issue is pandas, you need to downgrade pandas

**Comment by iamdionysus** [comment]
For your information, I just had this issue and have tested with different pandas version. `pandas` version from 1.0 to 1.1 has worked.
